# This file is automatically generated by pyo3_stub_gen

import builtins
import enum
import os
import pathlib
import typing

import numpy as np
import numpy.typing as npt

__all__ = [
    "AnalysisResult",
    "Analyzer",
    "AudioConfigMismatchError",
    "AudioConfigUnsupportedError",
    "Collector",
    "FileAnalyzer",
    "FilePathInvalidError",
    "FileSystemError",
    "InternalError",
    "LicenseExpiredError",
    "LicenseFormatInvalidError",
    "LicenseVersionUnsupportedError",
    "Model",
    "ModelDataUnalignedError",
    "ModelDownloadError",
    "ModelInvalidError",
    "ModelTypeUnsupportedError",
    "ModelVersionUnsupportedError",
    "NotInitializedError",
    "OtelConfig",
    "ParameterFixedError",
    "ParameterOutOfRangeError",
    "ProcessingNotAllowedError",
    "Processor",
    "ProcessorAsync",
    "ProcessorConfig",
    "ProcessorContext",
    "ProcessorParameter",
    "TokenUnsupportedError",
    "UnknownError",
    "Vad",
    "VadAsync",
    "VadContext",
    "VadParameter",
    "analyzer_pair",
    "get_compatible_model_version",
    "get_sdk_version",
    "set_sdk_id",
]

@typing.final
class AnalysisResult:
    r"""
    The result of analyzing an audio signal with an Analyzer.

    Scores are in the range 0.0 to 1.0. For all fields except speaker_loudness, lower values
    indicate less problematic audio.
    """
    @property
    def risk_score(self) -> builtins.float:
        r"""
        Headline audio score.

        Predicts likelihood of failure of downstream models including speech-to-text,
        voice activity detection or turn-taking or speech-to-speech models.
        Lower indicates less problematic audio.

        Range: 0.0 to 1.0
        """
    @property
    def speaker_reverb(self) -> builtins.float:
        r"""
        Measure of speaker distance and reverberance.
        Lower indicates less problematic audio.

        Range: 0.0 to 1.0
        """
    @property
    def speaker_loudness(self) -> builtins.float:
        r"""
        Measure of speaker loudness.

        Range: 0.0 to 1.0
        """
    @property
    def interfering_speech(self) -> builtins.float:
        r"""
        Measure of interference from additional speakers present in audio.
        Lower indicates less problematic audio.

        Range: 0.0 to 1.0
        """
    @property
    def media_speech(self) -> builtins.float:
        r"""
        Measure of interfering speech content from media devices,
        e.g. from TVs, radios, phones or else.
        Lower indicates less problematic audio.

        Range: 0.0 to 1.0
        """
    @property
    def noise(self) -> builtins.float:
        r"""
        Measure of ambient or environmental noise.
        Lower indicates less problematic audio.

        Range: 0.0 to 1.0
        """
    @property
    def packet_loss(self) -> builtins.float:
        r"""
        Measure of audio dropouts or discontinuities in the stream,
        e.g. from packet loss, frame erasure, jitter or CPU overload.
        Lower indicates less problematic audio.

        Range: 0.0 to 1.0
        """

@typing.final
class Analyzer:
    r"""
    Runs an analysis model over the audio buffered by a Collector.

    The analyzer is designed to be run in a non-audio thread. Analysis models are computationally
    expensive and cannot run in the audio thread. The analyzer has access to the audio buffered by
    the collector and can access it safely across threads.

    Created via analyzer_pair().
    """
    def reset(self) -> None:
        r"""
        Clears all internal state and buffers.

        Call this when the audio stream is interrupted or when seeking to prevent mispredictions
        from previous audio content. This operates on both the analyzer and its collector. The
        collector stays initialized to the configured settings.

        Thread Safety:
            Real-time safe. Can be called from audio processing threads.

        Example:
            >>> analyzer.reset()
        """
    def analyze_buffered(self) -> AnalysisResult:
        r"""
        Analyzes the buffered signal.

        The analyzer runs a forward-pass of the analysis model with a fixed length of audio,
        determined by the model. If this function is called before the collector has buffered
        that length of audio, the analyzer runs the analysis with silence (zeros) in the tail of
        the input.

        Returns:
            An AnalysisResult.

        Note:
            This function is not real-time safe. Avoid calling it from audio threads.

        Example:
            >>> result = analyzer.analyze_buffered()
            >>> print(result.risk_score)
        """
    def terminate_session(self) -> None:
        r"""
        Terminates the analyzer's telemetry session.

        The analyzer cannot analyze more audio after this call. The session is also terminated
        automatically when the analyzer is destroyed.

        Warning:
            This method may block and is not real-time safe.
        """
    def update_bearer_token(self, token: builtins.str) -> None:
        r"""
        Replaces the bearer token on the analyzer.

        Use this when your license key is a JWT and needs to be refreshed before it expires.
        Audio processing continues uninterrupted and the new token is used for all subsequent
        authentication. Both the original key and the new token must be JWTs; otherwise a
        `TokenUnsupportedError` is raised and the existing token stays in use.

        Args:
            token: The new JWT to install.

        Raises:
            TokenUnsupportedError: If either the original or new token is not a JWT.
            LicenseFormatInvalidError: If the token string contains null bytes.

        Example:
            >>> analyzer.update_bearer_token(renewed_jwt)
        """

@typing.final
class AudioConfigMismatchError(builtins.Exception):
    r"""
    Audio configuration differs from the one provided during initialization.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> AudioConfigMismatchError: ...

@typing.final
class AudioConfigUnsupportedError(builtins.Exception):
    r"""
    Audio configuration (sample_rate, block_size) is not supported by the model.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> AudioConfigUnsupportedError: ...

@typing.final
class Collector:
    r"""
    Buffers audio for later analysis.

    The collector is designed to be placed in the audio thread, buffering audio chunks for the
    Analyzer to analyze later.

    Created via analyzer_pair().
    """
    def initialize(self, config: ProcessorConfig) -> None:
        r"""
        Configures the collector for specific audio settings.

        This function must be called before buffering any audio.
        Using the sample rate and block size returned by Model.get_optimal_sample_rate()
        and Model.get_optimal_block_size() avoids internal resampling and rebuffering.

        Args:
            config: Audio buffering configuration

        Raises:
            ValueError: If the audio configuration is unsupported.

        Warning:
            Do not call from audio processing threads as this allocates memory.

        Example:
            >>> config = aic.ProcessorConfig.optimal(model)
            >>> collector.initialize(config)
        """
    def buffer(self, buffer: npt.NDArray[np.float32]) -> None:
        r"""
        Buffers audio from a 1D NumPy array of mono float32 samples for later analysis.

        Args:
            buffer: 1D NumPy array of mono float32 samples to be buffered.

        Raises:
            NotInitializedError: If the collector has not been initialized.
            AudioConfigMismatchError: If the buffer shape doesn't match the configured audio settings.

        Example:
            >>> audio = np.zeros(config.block_size, dtype=np.float32)
            >>> collector.buffer(audio)
        """

@typing.final
class FileAnalyzer:
    r"""
    Analyzes complete mono audio buffers.

    FileAnalyzer is a convenience wrapper around a Collector and Analyzer pair for non-real-time
    analysis of audio that is already loaded in memory.

    Each call to analyze() configures the collector for mono input with the model's optimal block
    size. It analyzes independent five-second windows, advancing the start of each window by
    step_samples.

    For streaming or multi-channel analysis, use analyzer_pair() directly.

    Example:

        >>> analyzer = aic.FileAnalyzer(model, license_key)
        >>> results = analyzer.analyze(audio, 16000)
        >>> print(results[0].risk_score)
    """
    def __new__(cls, model: Model, license_key: builtins.str) -> FileAnalyzer:
        r"""
        Creates a new file analyzer.

        The collector is not initialized until analyze() is called. This lets the same FileAnalyzer
        instance analyze mono buffers with different sample rates or step sizes.

        Args:
            model: The loaded model instance
            license_key: License key for the ai-coustics SDK
                (generate your key at <https://developers.ai-coustics.com/>)

        Raises:
            LicenseFormatInvalidError: If the license key string contains null bytes.
            RuntimeError: If the analyzer pair cannot be created.

        Example:
            >>> analyzer = aic.FileAnalyzer(model, license_key)
        """
    def analyze(
        self,
        audio: npt.NDArray[np.float32],
        sample_rate: builtins.int,
        step_samples: builtins.int | None = None,
    ) -> builtins.list[AnalysisResult]:
        r"""
        Analyzes a complete mono audio buffer.

        The input must contain mono float32 samples at sample_rate. No channel mixing
        or resampling is performed.

        The analyzer evaluates five-second windows. FileAnalyzer buffers a window starting
        at sample 0, runs the analyzer once, resets, then repeats with a window starting
        step_samples later. If audio is shorter than or equal to five seconds, it is padded
        with silence and a single result is returned. For longer signals, only complete
        five-second windows are analyzed after the first window.

        Args:
            audio: 1D NumPy array of mono float32 samples to analyze.
            sample_rate: Sample rate of audio in Hz.
            step_samples: Number of samples to advance between analysis results. Defaults
                   to the model's window size (no overlap) if None.

        Returns:
            A list of AnalysisResult values, one per analysis window.

        Raises:
            AudioConfigUnsupportedError: If the sample rate or step size is unsupported.

        Example:
            >>> results = analyzer.analyze(audio, 16000)
            >>> print(results[0].risk_score)
        """

@typing.final
class FilePathInvalidError(builtins.Exception):
    r"""
    The file path is invalid.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> FilePathInvalidError: ...

@typing.final
class FileSystemError(builtins.Exception):
    r"""
    The model file cannot be opened due to a filesystem error. Verify that the file exists.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> FileSystemError: ...

@typing.final
class InternalError(builtins.Exception):
    r"""
    Internal error occurred. Contact support.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> InternalError: ...

@typing.final
class LicenseExpiredError(builtins.Exception):
    r"""
    License key has expired. Renew your license to continue.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> LicenseExpiredError: ...

@typing.final
class LicenseFormatInvalidError(builtins.Exception):
    r"""
    License key format is invalid or corrupted. Verify the key was copied correctly.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> LicenseFormatInvalidError: ...

@typing.final
class LicenseVersionUnsupportedError(builtins.Exception):
    r"""
    License version is not compatible with the SDK version. Update SDK or contact support.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> LicenseVersionUnsupportedError: ...

@typing.final
class Model:
    r"""
    High-level wrapper for an ai-coustics model.

    This class provides a safe, Python-friendly interface to the underlying C library.
    It handles memory management automatically.

    Example:
        >>> model = Model.from_file("/path/to/model.aicmodel")
        >>> processor = Processor(model, license_key)
        >>> config = ProcessorConfig.optimal(model)
        >>> processor.initialize(config)
    """
    @staticmethod
    def from_file(path: builtins.str | os.PathLike | pathlib.Path) -> Model:
        r"""
        Creates a new model instance from a file.

        Multiple models can be loaded for enhancement, voice activity detection, or analysis.

        Args:
            path: Path to the model file (.aicmodel). You can download models manually
                from <https://artifacts.ai-coustics.io> or use Model.download() to fetch
                them programmatically. Accepts both string paths and pathlib.Path objects.

        Returns:
            A new Model instance.

        Raises:
            RuntimeError: If model creation fails.

        See Also:
            <https://artifacts.ai-coustics.io> for available model IDs and downloads.

        Example:
            >>> model = Model.from_file("/path/to/model.aicmodel")
            >>> model = Model.from_file(Path.cwd() / "model.aicmodel"))
        """
    @staticmethod
    def download(
        model_id: builtins.str, download_dir: builtins.str | os.PathLike | pathlib.Path
    ) -> builtins.str:
        r"""
        Downloads a model file from the ai-coustics artifact CDN.

        This method fetches the model manifest, verifies that the requested model
        exists in a version compatible with this library, and downloads the model
        file to the specified directory. If the model file already exists, it will not
        be re-downloaded. If the existing file's checksum does not match, the model will
        be downloaded and the existing file will be replaced.

        The manifest file is not cached and will always be downloaded on every call
        to ensure the latest model versions are always used.

        Available models can be browsed at [artifacts.ai-coustics.io](https://artifacts.ai-coustics.io/).

        Note:
            This is a blocking operation that performs network I/O.

        Args:
            model_id: The model identifier (e.g., `"quail-l-16khz"`).
            download_dir: Directory where the model file will be stored.

        Returns:
            The full path to the model file.

        Raises:
            RuntimeError: If the operation fails.

        Example:
            >>> # Find model IDs at <https://artifacts.ai-coustics.io>
            >>> path = Model.download("rook-l-16khz", "/tmp/models")
            >>>
            >>> # Or using pathlib.Path
            >>> path = Model.download("rook-l-16khz", Path(tempfile.gettempdir()) / "models"))
            >>>
            >>> model = Model.from_file(path)
        """
    @staticmethod
    def download_async(
        model_id: builtins.str, download_dir: builtins.str | os.PathLike | pathlib.Path
    ) -> typing.Any:
        r"""
        Downloads a model file asynchronously from the ai-coustics artifact CDN.

        This method fetches the model manifest, verifies that the requested model
        exists in a version compatible with this library, and downloads the model
        file to the specified directory. If the model file already exists, it will not
        be re-downloaded. If the existing file's checksum does not match, the model will
        be downloaded and the existing file will be replaced.

        The manifest file is not cached and will always be downloaded on every call
        to ensure the latest model versions are always used.

        Available models can be browsed at [artifacts.ai-coustics.io](https://artifacts.ai-coustics.io/).

        Note:
            This is a blocking operation that performs network I/O.

        Args:
            model_id: The model identifier (e.g., `"quail-l-16khz"`).
            download_dir: Directory where the model file will be stored.

        Returns:
            The full path to the model file.

        Raises:
            RuntimeError: If the operation fails.

        Example:
            >>> # Find model IDs at <https://artifacts.ai-coustics.io>
            >>> path = await Model.download_async("rook-l-16khz", "/tmp/models")
            >>>
            >>> # Or using pathlib.Path
            >>> path = await Model.download_async("rook-l-16khz", Path(tempfile.gettempdir()) / "models"))
            >>>
            >>> model = Model.from_file(path)
        """
    def get_id(self) -> builtins.str:
        r"""
        Returns the model identifier string.

        Returns:
            The model ID string.
        """
    def get_optimal_sample_rate(self) -> builtins.int:
        r"""
        Retrieves the native sample rate of the model.

        Each model is optimized for a specific sample rate, which determines the frequency
        range of the enhanced audio output. While you can process audio at any sample rate,
        understanding the model's native rate helps predict the enhancement quality.

        How sample rate affects enhancement:
            - Models trained at lower sample rates (e.g., 8 kHz) can only enhance frequencies
              up to their Nyquist limit (4 kHz for 8 kHz models)
            - When processing higher sample rate input (e.g., 48 kHz) with a lower-rate model,
              only the lower frequency components will be enhanced

        Enhancement blending:
            When enhancement strength is set below 1.0, the enhanced signal is blended with
            the original, maintaining the full frequency spectrum of your input while adding
            the model's noise reduction capabilities to the lower frequencies.

        Sample rate and optimal block size relationship:
            When using a different sample rate than the model's native rate, the optimal block
            size (returned by get_optimal_block_size) changes. The model's output delay remains
            constant as long as you use the optimal block size for that rate.

        Recommendation:
            For maximum enhancement quality across the full frequency spectrum, match your
            input sample rate to the model's native rate when possible.

        Returns:
            The model's native sample rate in Hz.

        Example:
            >>> optimal_rate = model.get_optimal_sample_rate()
            >>> print(f"Optimal sample rate: {optimal_rate} Hz")
        """
    def get_optimal_block_size(self, sample_rate: builtins.int) -> builtins.int:
        r"""
        Retrieves the optimal block size for the model at a given sample rate.

        Using the optimal block size minimizes latency by avoiding internal buffering.
        A non-optimal block size adds buffering latency on top of the model's base delay.

        The optimal block size varies with sample rate because each model operates on a fixed
        time window. For example, a 10 ms window is 480 samples at 48 kHz and 160 samples at
        16 kHz.

        Args:
            sample_rate: Sample rate in Hz for which to calculate the optimal block size

        Returns:
            The optimal block size for the given sample rate.

        Example:
            >>> sample_rate = model.get_optimal_sample_rate()
            >>> block_size = model.get_optimal_block_size(sample_rate)
            >>> print(f"Optimal block size: {block_size}")
        """

@typing.final
class ModelDataUnalignedError(builtins.Exception):
    r"""
    The model data is not aligned to 64 bytes.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> ModelDataUnalignedError: ...

@typing.final
class ModelDownloadError(builtins.Exception):
    r"""
    Model download error occurred.
    """
    @property
    def message(self) -> builtins.str: ...
    @property
    def details(self) -> builtins.str: ...
    def __new__(
        cls, message: builtins.str, details: builtins.str
    ) -> ModelDownloadError: ...

@typing.final
class ModelInvalidError(builtins.Exception):
    r"""
    The model file is invalid or corrupted. Verify the file is correct.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> ModelInvalidError: ...

@typing.final
class ModelTypeUnsupportedError(builtins.Exception):
    r"""
    The model type is not supported by this operation.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> ModelTypeUnsupportedError: ...

@typing.final
class ModelVersionUnsupportedError(builtins.Exception):
    r"""
    The model file version is not compatible with this SDK version.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> ModelVersionUnsupportedError: ...

@typing.final
class NotInitializedError(builtins.Exception):
    r"""
    Handle must be initialized before this operation. Call `Processor.initialize`, `Vad.initialize`, or `Collector.initialize` first.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> NotInitializedError: ...

@typing.final
class OtelConfig:
    r"""
    OpenTelemetry configuration for a Processor or Vad.

    Pass to Processor, ProcessorAsync, Vad, or VadAsync to control telemetry per instance.
    When no OtelConfig is provided, telemetry is configured according to the runtime
    environment (e.g. the AIC_SDK_OTEL_ENABLE environment variable).

    Example:
        >>> processor = Processor(model, license_key, otel_config=OtelConfig(enable=True, session_id="my-session"))
    """
    @property
    def enable(self) -> builtins.bool:
        r"""
        Whether to enable OpenTelemetry telemetry.
        Overrides the AIC_SDK_OTEL_ENABLE environment variable.
        """
    @enable.setter
    def enable(self, value: builtins.bool) -> None:
        r"""
        Whether to enable OpenTelemetry telemetry.
        Overrides the AIC_SDK_OTEL_ENABLE environment variable.
        """
    @property
    def session_id(self) -> builtins.str | None:
        r"""
        Optional session ID for telemetry. If None, a random session ID is generated.
        """
    @session_id.setter
    def session_id(self, value: builtins.str | None) -> None:
        r"""
        Optional session ID for telemetry. If None, a random session ID is generated.
        """
    @property
    def export_interval_ms(self) -> builtins.int:
        r"""
        OpenTelemetry metric export interval in milliseconds.
        Set to 0 to use the SDK default of 60,000 ms.
        """
    @export_interval_ms.setter
    def export_interval_ms(self, value: builtins.int) -> None:
        r"""
        OpenTelemetry metric export interval in milliseconds.
        Set to 0 to use the SDK default of 60,000 ms.
        """
    def __new__(
        cls,
        enable: builtins.bool,
        session_id: builtins.str | None = None,
        export_interval_ms: builtins.int = 0,
    ) -> OtelConfig:
        r"""
        Creates a new OtelConfig instance.

        Args:
            enable: Whether to enable OpenTelemetry telemetry
            session_id: Optional session ID. If None, a random ID is generated.
            export_interval_ms: Metric export interval in ms. 0 uses the SDK default (60,000 ms).
        """

@typing.final
class ParameterFixedError(builtins.Exception):
    r"""
    The requested parameter is read-only for this model type and cannot be modified.

    .. deprecated::
        This error is no longer raised by the SDK.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> ParameterFixedError: ...

@typing.final
class ParameterOutOfRangeError(builtins.Exception):
    r"""
    Parameter value is outside the acceptable range. Check documentation for valid values.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> ParameterOutOfRangeError: ...

@typing.final
class ProcessingNotAllowedError(builtins.Exception):
    r"""
    Processing is not allowed because the SDK key was not authorized or usage reporting failed.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> ProcessingNotAllowedError: ...

@typing.final
class Processor:
    r"""
    High-level wrapper for the ai-coustics audio enhancement processor.

    This class provides a safe, Python-friendly interface to the underlying C library.
    It handles memory management automatically.

    Example:
        >>> model = Model.from_file("/path/to/model.aicmodel")
        >>> processor = Processor(model, license_key)
        >>> config = ProcessorConfig.optimal(model)
        >>> processor.initialize(config)
        >>> audio = np.zeros(config.block_size, dtype=np.float32)
        >>> enhanced = processor.process(audio)
    """
    def __new__(
        cls,
        model: Model,
        license_key: builtins.str,
        config: ProcessorConfig | None = None,
        otel_config: OtelConfig | None = None,
    ) -> Processor:
        r"""
        Creates a new audio enhancement processor instance.

        Multiple processors can be created to process different audio streams simultaneously
        or to switch between different enhancement algorithms during runtime.

        If a config is provided, the processor will be initialized immediately.
        Otherwise, you must call initialize() before processing audio.

        Args:
            model: The loaded enhancement or bypass model instance
            license_key: License key for the ai-coustics SDK
                (generate your key at <https://developers.ai-coustics.com/>)
            config: Optional audio processing configuration. If provided, the processor
                will be initialized immediately with this configuration.

        Raises:
            RuntimeError: If processor creation fails.
            ValueError: If config is provided and the audio configuration is unsupported.

        Example:
            >>> # Create processor without initialization
            >>> processor = Processor(model, license_key)
            >>> processor.initialize(config)

            >>> # Or create and initialize in one step
            >>> config = ProcessorConfig.optimal(model)
            >>> processor = Processor(model, license_key, config)
        """
    def initialize(self, config: ProcessorConfig) -> None:
        r"""
        Configures the processor for specific audio settings.

        This function must be called before processing any audio.
        For the lowest delay use the sample rate and block size returned by
        Model.get_optimal_sample_rate() and Model.get_optimal_block_size().

        Args:
            config: Audio processing configuration

        Raises:
            ValueError: If the audio configuration is unsupported.

        Warning:
            Do not call from audio processing threads as this allocates memory.

        Example:
            >>> config = ProcessorConfig.optimal(model)
            >>> processor.initialize(config)
        """
    def process(self, audio: npt.NDArray[np.float32]) -> npt.NDArray[np.float32]:
        r"""
        Enhances a mono float32 audio block and returns the processed block.

        Raises:
            NotInitializedError: If the processor has not been initialized.
            AudioConfigMismatchError: If the block size does not match the configuration.
            ProcessingNotAllowedError: If processing is not authorized.
        """
    def get_context(self) -> ProcessorContext:
        r"""
        Creates a ProcessorContext instance.

        This can be used to control all parameters and other settings of the processor.

        Returns:
            A new ProcessorContext instance.

        Example:
            >>> processor_context = processor.get_context()
        """
    def terminate_session(self) -> None:
        r"""
        Terminates the processor's telemetry session.

        The processor cannot process more audio after this call. The session is also
        terminated automatically when the processor is destroyed.

        Warning:
            This method may block and is not real-time safe.
        """

@typing.final
class ProcessorAsync:
    r"""
    Async wrapper for Processor that offloads work to background threads.

    This class provides the same functionality as Processor but with async methods
    that don't block the event loop. Processing thread count is controlled by the
    `AIC_NUM_THREADS` environment variable.

    Example:
        >>> model = Model.from_file("/path/to/model.aicmodel")
        >>> processor = ProcessorAsync(model, license_key)
        >>> config = ProcessorConfig.optimal(model)
        >>> await processor.initialize_async(config)
        >>> audio = np.zeros(config.block_size, dtype=np.float32)
        >>> enhanced = await processor.process_async(audio)
    """
    def __new__(
        cls,
        model: Model,
        license_key: builtins.str,
        config: ProcessorConfig | None = None,
        otel_config: OtelConfig | None = None,
    ) -> ProcessorAsync:
        r"""
        Creates a new async audio enhancement processor instance.

        Multiple processors can be created to process different audio streams simultaneously
        or to switch between different enhancement algorithms during runtime.

        If a config is provided, the processor will be initialized immediately.
        Otherwise, you must call initialize_async() before processing audio.

        Args:
            model: The loaded enhancement or bypass model instance
            license_key: License key for the ai-coustics SDK
                (generate your key at <https://developers.ai-coustics.io/>)
            config: Optional audio processing configuration. If provided, the processor
                will be initialized immediately with this configuration.

        Raises:
            RuntimeError: If processor creation fails.
            ValueError: If config is provided and the audio configuration is unsupported.

        Example:
            >>> # Create processor without initialization
            >>> processor = ProcessorAsync(model, license_key)
            >>> await processor.initialize_async(config)

            >>> # Or create and initialize in one step
            >>> config = ProcessorConfig.optimal(model)
            >>> processor = ProcessorAsync(model, license_key, config)
        """
    def initialize_async(self, config: ProcessorConfig) -> typing.Awaitable[None]:
        r"""
        Configures the processor asynchronously for specific audio settings.

        This function must be called before processing any audio.
        For the lowest delay use the sample rate and block size returned by
        Model.get_optimal_sample_rate() and Model.get_optimal_block_size().

        Args:
            config: Audio processing configuration

        Raises:
            ValueError: If the audio configuration is unsupported.

        Example:
            >>> config = ProcessorConfig.optimal(model)
            >>> await processor.initialize_async(config)
        """
    async def process_async(
        self, audio: npt.NDArray[np.float32]
    ) -> npt.NDArray[np.float32]:
        r"""
        Enhances a mono float32 audio block on a background thread.

        Raises:
            NotInitializedError: If the processor has not been initialized.
            AudioConfigMismatchError: If the block size does not match the configuration.
            ProcessingNotAllowedError: If processing is not authorized.
        """
    def get_context(self) -> ProcessorContext:
        r"""
        Returns a ProcessorContext for real-time parameter control.

        Returns:
            A new ProcessorContext instance.

        Example:
            >>> processor_context = processor.get_context()
        """
    def terminate_session_async(self) -> typing.Awaitable[None]:
        r"""
        Terminates the processor's telemetry session asynchronously.

        The processor cannot process more audio after this call.
        """

@typing.final
class ProcessorConfig:
    r"""
    Audio configuration passed to Processor.initialize(), Vad.initialize(),
    and Collector.initialize().

    Use ProcessorConfig.optimal() as a starting point, then adjust fields
    to match your audio stream.
    """
    @property
    def sample_rate(self) -> builtins.int:
        r"""
        Sample rate in Hz (8000 - 192000)
        """
    @sample_rate.setter
    def sample_rate(self, value: builtins.int) -> None:
        r"""
        Sample rate in Hz (8000 - 192000)
        """
    @property
    def block_size(self) -> builtins.int:
        r"""
        Number of samples provided to each processing call.
        Note that using a non-optimal block size increases latency.
        """
    @block_size.setter
    def block_size(self, value: builtins.int) -> None:
        r"""
        Number of samples provided to each processing call.
        Note that using a non-optimal block size increases latency.
        """
    @property
    def variable_block_size(self) -> builtins.bool:
        r"""
        Allows calls shorter than block_size at the cost of added latency.
        """
    @variable_block_size.setter
    def variable_block_size(self, value: builtins.bool) -> None:
        r"""
        Allows calls shorter than block_size at the cost of added latency.
        """
    def __new__(
        cls,
        sample_rate: builtins.int,
        block_size: builtins.int,
        variable_block_size: builtins.bool = False,
    ) -> ProcessorConfig:
        r"""
        Create a new ProcessorConfig instance.

        Args:
            sample_rate: Sample rate in Hz (8000 - 192000)
            block_size: Number of samples provided to each processing call
            variable_block_size: Allow calls shorter than block_size (default: False)
        """
    @staticmethod
    def optimal(
        model: Model,
        sample_rate: builtins.int | None = None,
        block_size: builtins.int | None = None,
        variable_block_size: builtins.bool = False,
    ) -> ProcessorConfig:
        r"""
        Returns a ProcessorConfig pre-filled with the model's optimal settings.

        This method provides a convenient way to create a config with optimal defaults
        while allowing you to override specific parameters as needed.

        Args:
            model: The Model instance to get optimal config for
            sample_rate: Custom sample rate in Hz. If None, uses the model's optimal sample rate (default: None)
            block_size: Custom number of samples per processing call. If None, uses the optimal block size
                for the sample rate (default: None). A non-optimal block size increases latency.
            variable_block_size: Allow calls shorter than block_size (default: False)

        Returns:
            ProcessorConfig with optimal settings for the given model.

        Example:
            >>> # Use all optimal defaults
            >>> config = ProcessorConfig.optimal(model)
            >>> # Use a custom sample rate (optimal block size calculated automatically)
            >>> config = ProcessorConfig.optimal(model, sample_rate=44100)
            >>> # Use a custom sample rate and block size (increases latency)
            >>> config = ProcessorConfig.optimal(model, sample_rate=48000, block_size=512)
        """

@typing.final
class ProcessorContext:
    r"""
    Context for managing processor state and parameters.

    Created via Processor.get_context().
    """
    def reset(self) -> None:
        r"""
        Clears all internal enhancement state and buffers.

        Call this when the audio stream is interrupted or when seeking
        to prevent artifacts from previous audio content.

        The processor stays initialized to the configured settings.

        Thread Safety:
            Real-time safe. Can be called from audio processing threads.

        Example:
            >>> processor_context.reset()
        """
    def set_parameter(
        self, parameter: ProcessorParameter, value: builtins.float
    ) -> None:
        r"""
        Modifies a processor parameter.

        All parameters can be changed during audio processing.
        This function can be called from any thread.

        Args:
            parameter: Parameter to modify
            value: New parameter value. See parameter documentation for ranges

        Raises:
            ValueError: If the parameter value is out of range.

        Example:
            >>> processor_context.set_parameter(ProcessorParameter.EnhancementLevel, 0.8)
        """
    def get_parameter(self, parameter: ProcessorParameter) -> builtins.float:
        r"""
        Retrieves the current value of a parameter.

        This function can be called from any thread.

        Args:
            parameter: Parameter to query

        Returns:
            The current parameter value.

        Example:
            >>> level = processor_context.get_parameter(ProcessorParameter.EnhancementLevel)
            >>> print(f"Current enhancement level: {level}")
        """
    def parameter(self, parameter: ProcessorParameter) -> builtins.float:
        r"""
        Deprecated: Use get_parameter instead
        """
    def get_audio_delay(self) -> builtins.int:
        r"""
        Returns the delay applied to the audio in samples for the current audio configuration.

        This function provides the complete end-to-end enhancement latency, including
        algorithmic processing delay and buffering overhead. The processed audio leaves
        Processor.process() this many samples behind its input.

        It does not include VAD delay; use VadContext.get_prediction_delay() for a separate VAD.

        Delay behavior:
            - Before initialization: Returns the base processing delay using the model's
              optimal block size at its native sample rate
            - After initialization: Returns the actual delay for your specific configuration,
              including any additional buffering introduced by a non-optimal block size

        Important:
            The delay value is always expressed in samples at the sample rate
            you configured during initialize(). To convert to time units:
            delay_ms = (delay_samples * 1000) / sample_rate

        Note:
            Using a block size different from the optimal value returned by
            get_optimal_block_size() will increase the delay beyond the model's base latency.

        Returns:
            The delay in samples.

        Example:
            >>> delay = processor_context.get_audio_delay()
            >>> print(f"Audio delay: {delay} samples")
        """
    def update_bearer_token(self, token: builtins.str) -> None:
        r"""
        Replaces the bearer token on the running processor.

        Use this when your license key is a JWT and needs to be refreshed before it expires.
        Audio processing continues uninterrupted and the new token is used for all subsequent
        authentication. Both the original key and the new token must be JWTs; otherwise a
        `TokenUnsupportedError` error is raised and the existing token stays in use.

        Args:
            token: The new JWT to install.

        Raises:
            TokenUnsupportedError: If either the original or new token is not a JWT.
            LicenseFormatInvalidError: If the token string contains null bytes.

        Example:
            >>> processor_context.update_bearer_token(renewed_jwt)
        """

@typing.final
class TokenUnsupportedError(builtins.Exception):
    r"""
    Updating the token is only supported when both the original and new keys are JWT-form licenses.
    """
    @property
    def message(self) -> builtins.str: ...
    def __new__(cls, message: builtins.str) -> TokenUnsupportedError: ...

@typing.final
class UnknownError(builtins.Exception):
    r"""
    Unknown error code encountered.
    """
    @property
    def message(self) -> builtins.str: ...
    @property
    def error_code(self) -> builtins.int: ...
    def __new__(
        cls, message: builtins.str, error_code: builtins.int
    ) -> UnknownError: ...

@typing.final
class Vad:
    r"""
    Voice activity detector backed by a dedicated VAD model.

    Feed mono audio to process() and read predictions through get_context(). The audio is not
    modified; processing only updates the detector's prediction.

    When enhancement and VAD run together, feed the VAD the original input audio, not the
    enhanced output of Processor.process(). Run both on the same block instead of chaining them:

        >>> vad.process(audio)                   # reads the block, does not modify it
        >>> enhanced = processor.process(audio)  # enhances the same original block

    Example:
        >>> model = Model.from_file("/path/to/vad_model.aicmodel")
        >>> config = ProcessorConfig.optimal(model)
        >>> vad = Vad(model, license_key, config)
        >>> vad_context = vad.get_context()
        >>> audio = np.zeros(config.block_size, dtype=np.float32)
        >>> vad.process(audio)
        >>> print(vad_context.is_speech_detected())
    """
    def __new__(
        cls,
        model: Model,
        license_key: builtins.str,
        config: ProcessorConfig | None = None,
        otel_config: OtelConfig | None = None,
    ) -> Vad:
        r"""
        Creates a voice activity detector.

        The model must be a dedicated VAD model, such as vad-2.1-xxs-16khz. Enhancement models
        raise ModelTypeUnsupportedError.

        If config is provided, the VAD is initialized immediately. Otherwise, call initialize()
        before processing audio.

        Args:
            model: A loaded dedicated VAD model
            license_key: License key for the ai-coustics SDK
            config: Optional audio configuration
            otel_config: Optional per-instance OpenTelemetry configuration
        """
    def initialize(self, config: ProcessorConfig) -> None:
        r"""
        Configures the VAD for a sample rate and block size.

        For the most frequent prediction updates, use ProcessorConfig.optimal(model).

        Args:
            config: Audio configuration

        Warning:
            This method allocates memory and is not real-time safe.
        """
    def process(self, audio: npt.NDArray[np.float32]) -> None:
        r"""
        Processes a mono float32 audio block and updates the VAD prediction.

        Returns nothing: VAD processing does not modify the audio. Read the updated
        prediction through get_context().

        When enhancement and VAD run together, pass the original input audio here, not
        the enhanced output of Processor.process().

        Raises:
            NotInitializedError: If the VAD has not been initialized.
            AudioConfigMismatchError: If the block size does not match the configuration.
            ProcessingNotAllowedError: If processing is not authorized.
        """
    def get_context(self) -> VadContext:
        r"""
        Returns a context for reading predictions and controlling the VAD.
        """
    def terminate_session(self) -> None:
        r"""
        Terminates the VAD's telemetry session.

        The VAD cannot process more audio after this call. The session is also terminated
        automatically when the VAD is destroyed.

        Warning:
            This method may block and is not real-time safe.
        """

@typing.final
class VadAsync:
    r"""
    Async voice activity detector backed by a dedicated VAD model.

    Processing runs on the SDK's background thread pool and does not block the event loop.

    When enhancement and VAD run together, feed the VAD the original input audio, not the
    enhanced output of ProcessorAsync.process_async().
    """
    def __new__(
        cls,
        model: Model,
        license_key: builtins.str,
        config: ProcessorConfig | None = None,
        otel_config: OtelConfig | None = None,
    ) -> VadAsync:
        r"""
        Creates an async voice activity detector.

        The model must be a dedicated VAD model, such as vad-2.1-xxs-16khz. Enhancement models
        raise ModelTypeUnsupportedError.

        Args:
            model: A loaded dedicated VAD model
            license_key: License key for the ai-coustics SDK
            config: Optional audio configuration
            otel_config: Optional per-instance OpenTelemetry configuration
        """
    def initialize_async(self, config: ProcessorConfig) -> typing.Awaitable[None]:
        r"""
        Configures the VAD asynchronously for a sample rate and block size.
        """
    async def process_async(self, audio: npt.NDArray[np.float32]) -> None:
        r"""
        Processes a mono float32 audio block and updates the VAD prediction on a background thread.

        Returns nothing: VAD processing does not modify the audio. Read the updated
        prediction through get_context().

        When enhancement and VAD run together, pass the original input audio here, not
        the enhanced output of ProcessorAsync.process_async().
        """
    def get_context(self) -> VadContext:
        r"""
        Returns a context for reading predictions and controlling the VAD.
        """
    def terminate_session_async(self) -> typing.Awaitable[None]:
        r"""
        Terminates the VAD's telemetry session asynchronously.

        The VAD cannot process more audio after this call.
        """

@typing.final
class VadContext:
    r"""
    Thread-safe context for a Vad.

    Contexts created by the same Vad reference the same detector. They can be used from any
    thread while audio is being processed elsewhere.
    """
    def is_speech_detected(self) -> builtins.bool:
        r"""
        Returns the post-processed VAD prediction.

        The prediction lags its input by get_prediction_delay() samples. If the backing Vad stops
        being processed, the prediction does not update.
        """
    def raw_vad_probability(self) -> builtins.float:
        r"""
        Returns the VAD model's raw speech probability without SDK post-processing.

        The prediction lags its input by get_prediction_delay() samples.
        """
    def set_parameter(self, parameter: VadParameter, value: builtins.float) -> None:
        r"""
        Modifies a VAD parameter.

        Args:
            parameter: Parameter to modify
            value: New parameter value
        """
    def get_parameter(self, parameter: VadParameter) -> builtins.float:
        r"""
        Retrieves the current value of a VAD parameter.
        """
    def parameter(self, parameter: VadParameter) -> builtins.float:
        r"""
        Deprecated: Use get_parameter instead.
        """
    def get_prediction_delay(self) -> builtins.int:
        r"""
        Returns the total VAD prediction delay in samples.

        This includes input reblocking, model processing, and buffering overhead for the current
        configuration. Use it to align speech decisions with the input timeline.

        This delay is not applied to the audio: Vad.process() leaves its input untouched. The
        value only describes how far behind its input the published prediction is, and it is
        independent of ProcessorContext.get_audio_delay().
        """
    def reset(self) -> None:
        r"""
        Clears the VAD's internal state and published predictions.

        The VAD remains initialized. Immediately after reset(), is_speech_detected() is False and
        raw_vad_probability() is 0.0.
        """
    def update_bearer_token(self, token: builtins.str) -> None:
        r"""
        Replaces the bearer token on the running VAD.

        Both the original key and new token must be JWTs.
        """

@typing.final
class ProcessorParameter(enum.Enum):
    r"""
    Configurable parameters for audio enhancement.
    """

    Bypass = ...
    r"""
    Controls whether audio processing is bypassed while preserving algorithmic delay.

    When enabled, the input audio passes through unmodified, but the output is still
    delayed by the same amount as during normal processing. This ensures seamless
    transitions when toggling enhancement on/off without audible clicks or timing shifts.

    Range: 0.0 to 1.0
        - 0.0: Enhancement active (normal processing)
        - 1.0: Bypass enabled (latency-compensated passthrough)

    Default: 0.0
    """
    EnhancementLevel = ...
    r"""
    A tunable parameter to optimize for specific STT engines, deployment environments,
    and user experience requirements.

    The exact behavior depends on the active model:
    - **Quail Models:** Controls how aggressively the model suppresses noise. When used
      with Quail Voice Focus, it also suppresses background and competing speech.
    - **Rook Models:** Controls the mixback and therefore the intensity of the
      enhancement.

    **Range:** 0.0 to 1.0
    """
    VoiceGain = ...
    r"""
    Compensates for perceived volume reduction after noise removal.

    .. deprecated::
        This parameter has no effect and will be removed in a future version.

    Range: 0.1 to 4.0 (linear amplitude multiplier)
        - 0.1: Significant volume reduction (-20 dB)
        - 1.0: No gain change (0 dB, default)
        - 2.0: Double amplitude (+6 dB)
        - 4.0: Maximum boost (+12 dB)

    Formula: Gain (dB) = 20 × log₁₀(value)

    Default: 1.0
    """

@typing.final
class VadParameter(enum.Enum):
    r"""
    Configurable parameters for voice activity detection.
    """

    SpeechHoldDuration = ...
    r"""
    Controls how long speech remains detected after the audio no longer contains speech.

    The duration is rounded to the closest model window length.

    Range: 0.0 to 300x model window length (seconds)

    Default: 0.03 (30 ms)
    """
    Sensitivity = ...
    r"""
    Probability threshold used to decide whether speech is detected.

    Dedicated VAD models output a speech probability for each processed audio block. A value
    above this threshold triggers a speech-detected decision.

    Range: 0.0 to 1.0

    Default: model-specific
    """
    MinimumSpeechDuration = ...
    r"""
    Controls how long speech must be present before it is considered detected.

    The duration is rounded to the closest model window length.

    Range: 0.0 to 1.0 (seconds)

    Default: 0.0
    """

def analyzer_pair(
    model: Model, license_key: builtins.str
) -> tuple[Collector, Analyzer]:
    r"""
    Creates a Collector/Analyzer pair for non-real-time analysis.

    The collector is designed to be placed in the audio thread, buffering audio chunks for
    later analysis. The analyzer is designed to be run separately, since analysis models are
    computationally expensive and cannot run in the audio thread. The analyzer has access to
    the audio buffered by the collector and can access it safely across threads.

    The collector retains a span of audio determined by the analysis model. As more samples
    get collected, old audio is discarded.

    Args:
        model: The loaded model instance
        license_key: License key for the ai-coustics SDK
            (generate your key at <https://developers.ai-coustics.com/>)

    Returns:
        A tuple of (Collector, Analyzer).

    Raises:
        LicenseFormatInvalidError: If the license key string contains null bytes.
        RuntimeError: If the pair cannot be created.

    Example:
        >>> collector, analyzer = aic.analyzer_pair(model, license_key)
        >>> config = aic.ProcessorConfig.optimal(model)
        >>> collector.initialize(config)
    """

def get_compatible_model_version() -> builtins.int:
    r"""
    Returns the model version number compatible with this SDK build.

    Returns:
        The compatible model version number.
    """

def get_sdk_version() -> builtins.str:
    r"""
    Returns the version of the ai-coustics core SDK library used by this package.

    Note:
        This is not necessarily the same as this package's version.

    Returns:
        The library version as a string.

    Example:
        >>> version = aic.get_sdk_version()
        >>> print(f"ai-coustics SDK version: {version}")
    """

def set_sdk_id(id: builtins.int) -> None: ...
