site_name: ai-coustics SDK for Python
site_description: Real-time speech enhancement SDK Python bindings
site_url: https://ai-coustics.github.io/aic-sdk-py/
repo_name: ai-coustics/aic-sdk-py
repo_url: https://github.com/ai-coustics/aic-sdk-py

theme:
  name: material
  logo: aic-logo-dark.svg
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            show_signature: true
            show_bases: false
            merge_init_into_class: true
            docstring_section_style: list
            filters:
              - '!^_'

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api.md
  - Low-level C Bindings: low-level-bindings.md
  - Examples: examples.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ai-coustics/aic-sdk-py

