name: Test Release Download

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to test (e.g., 0.5.1)'
        required: true
        default: '0.5.1'

jobs:
  test-download:
    name: Test download for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux-x86_64
            artifact_name: aic-sdk-x86_64-unknown-linux-gnu
            file_ext: tar.gz
          - platform: linux-aarch64
            artifact_name: aic-sdk-aarch64-unknown-linux-gnu
            file_ext: tar.gz
          - platform: macos-universal
            artifact_name: aic-sdk-macos-universal
            file_ext: tar.gz
          - platform: macos-arm64
            artifact_name: aic-sdk-aarch64-apple-darwin
            file_ext: tar.gz
          - platform: windows-x64
            artifact_name: aic-sdk-x86_64-pc-windows-msvc
            file_ext: zip

    steps:
    - name: Test artifact download
      env:
        GITHUB_TOKEN: ${{ secrets.AIC_SDK_ACCESS_TOKEN }}
      run: |
        VERSION="${{ github.event.inputs.version }}"
        ARTIFACT_URL="https://github.com/ai-coustics/aic-sdk/releases/download/${VERSION}/${{ matrix.artifact_name }}-${VERSION}.${{ matrix.file_ext }}"
        
        echo "Testing download from: $ARTIFACT_URL"
        
        # Test if the artifact exists and is downloadable
        HTTP_STATUS=$(curl -L -H "Authorization: token $GITHUB_TOKEN" \
                          -H "Accept: application/octet-stream" \
                          -w "%{http_code}" -o /dev/null -s \
                          "$ARTIFACT_URL")
        
        if [ "$HTTP_STATUS" = "200" ]; then
          echo "✅ Artifact ${{ matrix.platform }} is accessible"
          
          # Download and inspect the content
          curl -L -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/octet-stream" \
               "$ARTIFACT_URL" -o "artifact.${{ matrix.file_ext }}"
          
          if [[ "${{ matrix.file_ext }}" == "zip" ]]; then
            unzip -l "artifact.${{ matrix.file_ext }}"
          else
            tar -tzf "artifact.${{ matrix.file_ext }}"
          fi
        else
          echo "❌ Failed to download ${{ matrix.platform }} (HTTP $HTTP_STATUS)"
          exit 1
        fi 